title: ~/leetcode
author:
  name: Shivanshu Semwal
  email: semwalshivanshu.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Shivanshu, crafting code to create solutions and a better tomorrow.

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
minima:
  social_links:
     - { platform: github,         user_url: "https://github.com/shivanshu-semwal" }
     - { platform: linkedin,       user_url: "https://www.linkedin.com/in/shivanshu-semwal" }
  skin: auto

header_pages:
  - list.md
  - completed.md
  - remaining.md
  - tags.md

paginate: 100
paginate_path: "/project/page:num/"
